env:
  CODECOV_TOKEN = 56f042dc-16bc-4c1e-b3a2-19d2ded28186
language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
services:
    - postgresql
cache: cargo
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
- rustup component add rustfmt
- rustup component add clippy
- psql -c "CREATE DATABASE casbin;" -U postgres
- psql -c "CREATE USER casbin_rs WITH PASSWORD 'casbin_rs';" -U postgres

script:
- cargo clean
- cargo build
- cargo test
- cargo clippy -- -D warnings
- cargo fmt --all -- --check

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # upload report to codecov
    docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin sh -c "cargo tarpaulin --out Xml"
    bash <(curl -s https://codecov.io/bash)
  fi
