language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
services:
    - postgresql
    - mysql
cache: cargo
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
- rustup component add rustfmt
- rustup component add clippy
- psql -c "CREATE DATABASE casbin;" -U postgres
- psql -c "CREATE USER casbin_rs WITH PASSWORD 'casbin_rs';" -U postgres
- mysql -u root -e "CREATE DATABASE casbin;"
- mysql -u root -e "CREATE USER 'casbin_rs'@'localhost' IDENTIFIED BY 'casbin_rs'; GRANT ALL ON casbin.* TO 'casbin_rs'@'localhost';"

script:
- cargo clean
- cargo build --no-default-features --features postgres,runtime-async-std
- cargo test --no-default-features --features postgres,runtime-async-std
- cargo build --no-default-features --features mysql,runtime-async-std
- cargo test --no-default-features --features mysql,runtime-async-std
- cargo clippy -- -D warnings
- cargo fmt --all -- --check

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # upload report to codecov
    cargo install cargo-tarpaulin
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
