[package]
name = "diesel-adapter"
version = "0.1.0"
authors = ["Cheng JIANG <jiang.cheng@vip.163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casbin = { version = "0.1.1" }
diesel = { version = "1.4.3", features = ["r2d2"] }
cfg-if = "0.1"

[features]
default = ["postgres"]

postgres = ["diesel/postgres"]
mysql = ["diesel/mysql"]
